services:
  extension-api:
    image: extension-api
    build: 
      dockerfile: Dockerfile
      context: .
      tags:
        - extension-api
    networks:
      extension: 
        ipv4_address: 172.18.0.2
    ports: 
      - ${PORT}:${PORT}
    restart: always
    environment:
      PORT: ${PORT}
      # Escribir secreto para encriptar (cadena de caracteres alfanumericos de 256 caracteres)
      SECRET: ${SECRET}
      BDD_HOST: 172.18.0.3
      BDD_USER: ${BDD_USER}
      # Escribir contraseña de la base de datos
      BDD_PASSWORD: ${BDD_PASSWORD}
      BDD_DATABASE: faco_luz_extension
      BDD_PORT: ${BDD_PORT}
      BDD_TIMEOUT: ${BDD_TIMEOUT}
      BDD_CONECTION_LIMITS: ${BDD_CONECTION_LIMITS}
    volumes:
      - ${VOLUME_API}:/data

  extension-db:
    image: extension-db
    build:
      context: .
      dockerfile: Dockerfile-db
      tags: 
        - extension-db
    networks:
      extension: 
        ipv4_address: 172.18.0.3
    ports:
      - 3306:3306
    restart: always
    environment:
      # A condinuacion escribir la contraseña de la base de datos
      MARIADB_ROOT_PASSWORD: ${BDD_PASSWORD}
    volumes: 
      - ${VOLUME_DB}:/var/lib/mysql

networks:
  extension:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
